version: '3'
services:
  freqtrade:
    build: .
    container_name: freqtrade
    volumes:
      - ./user_data:/freqtrade/user_data
      - ./config.json:/freqtrade/config.json
    command: >
      trade --strategy ${STRATEGY:-StrategyTemplate} --config /freqtrade/config.json
    ports:
      - "8080:8080"
    env_file:
      - .env
